export const books = [
  {
    id:1,
    author: "J.K. Rowling",
    title: "Harry Potter and the Sorcerer's Stone",
    rating: 4.8,
    price: 1299,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7I3qZPLNroLt6s189pEGUCdt8Z-08jU-yniCX0LsguHMOvHN9H8vSta7qQdFQuyXsTo8&usqp=CAU",
  },
  {
    id:2,
    author: "George Orwell",
    title: "1984",
    rating: 4.6,
    price: 999,
    image:
      "https://static.insales-cdn.com/images/products/1/6688/532666912/large_2022-03-26-09-32-261648272746.jpg",
  },
  {
    id:3,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
  {
    id:4,
    author: "F. Scott Fitzgerald",
    title: "The Great Gatsby",
    rating: 4.4,
    price: 799,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvY5lboNynyzrpVG6AbAtvs1ltTHPm6RhQqBBbiQ7DAHBr3htG6XkjNresRCtQM_nZzHw&usqp=CAU",
  },
  {
    id:5,
    author: "Harper Lee",
    title: "To Kill a Mockingbird",
    rating: 4.7,
    price: 1099,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ0OyQX5jaTilNWVg1pm1Cj_EH0dTO-d8zixIJCEdU-cMG5bUScKtQ8kBmOd55MGki134&usqp=CAU",
  },
  {id:6,
    author: "Ernest Hemingway",
    title: "The Old Man and the Sea",
    rating: 4.3,
    price: 699,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8hvH6J0a7HHtlm_rXq5300IsEc1U_SmolppFWPdtr8lV57nvZcRmIn4FXfzmBZKJUSbc&usqp=CAU",
  },
   {id:7,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
   {id:8,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
   {id:9,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
   {id:10,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
   {id:11,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
   {id:12,
    author: "Jane Austen",
    title: "Pride and Prejudice",
    rating: 4.5,
    price: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR55js26NETvWGjwibUc0o1JcMBetB8qlr3hSXhgXLqVZ_wb-vCMWDcnCzchRlTzeKW3yA&usqp=CAU",
  },
];
